#apiVersion: v1
#kind: Service
#metadata:
#  name: postgres
#  namespace: tagger
#spec:
#  selector:
#    app: postgres
#  ports:
#    - protocol: TCP
#      port: 5432
#      targetPort: 5432
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres
  namespace: tagger
spec:
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: PGDATA
            value: /var/lib/postgresql/data/db
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

