apiVersion: v1
kind: ReplicationController
metadata:
        name:
                tagger-worker
spec:
        replicas: 1
        selector:
                app: tagger-worker
        template:
                metadata:
                        name: tagger-worker
                        labels:
                                app: tagger-worker
                spec:
                        containers:
                                - name: tagger-worker
                                  image: webeng.azurecr.io/tagger-worker
                        imagePullSecrets:
                                - name: regsecret
