apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name:
                kafka-manager
spec:
        replicas: 1
        template:
                metadata:
                        name: kafka-manager
                        labels:
                                app: kafka-manager
                spec:
                        containers:
                                - name: kafka-manager
                                  image: sheepkiller/kafka-manager
                                  ports:
                                          - containerPort: 9000
                                  env:
                                          - name: ZK_HOSTS
                                            value: "zookeeper.kafka.svc.cluster.local:2181"

